dist/BaseInput.js
dist/InputStrings.js
dist/SelectInput.js
dist/SpecialInput.js
dist/index.js
src/commons/exampleList.js
src/lib/BaseInput.js
src/lib/InputStrings.js
src/lib/SelectInput.js
src/lib/SpecialInput.js
src/lib/index.js
src/stories/index.js

List input

---

src/commons/clabehelper.js
src/commons/utils.js
src/lib/CLABEInput.js
src/lib/InputStrings.js
src/lib/InputWrapper.js
src/lib/index.js
src/stories/index.js

Input clabe

---

dist/RadioSwitch.js
dist/index.js
package.json
src/lib/RadioSwitch.js
src/lib/index.js
src/lib/styles/RadioSwitch.css
src/stories/index.js

- Agregar 'RadioSwitch' componente, los colores los toma del tema del padre.

Radio switch

---

dist/RadioSwitch.js
src/lib/RadioSwitch.js

fix colores

---

src/lib/Table/components/Tbody/index.jsx
src/lib/Table/components/Tbody/style.js
src/lib/Table/components/Thead/index.jsx
src/lib/Table/components/Thead/style.js
src/lib/Table/index.jsx
src/lib/Table/style.js
src/stories/index.js

table style

---

package-lock.json
src/lib/commons/exampleList.js
src/lib/nodes/Select/index.jsx
src/lib/nodes/Select/style.js
src/lib/nodes/index.js
src/stories/index.js

Add select

---

package.json
src/lib/Paginator/index.jsx
src/lib/Paginator/style.js
src/stories/index.js
yarn.lock

paginator component

---

package.json
src/lib/DatePicker/index.jsx
src/lib/DatePicker/style.js
src/lib/Paginator/index.jsx
src/lib/Paginator/style.js
src/stories/index.js
yarn.lock

Date picker

---

.vscode/settings.json
src/lib/RejectionNote/index.jsx
src/lib/RejectionNote/style.js
src/stories/index.js

Rejection note

---

src/lib/Paginator/index.jsx
src/stories/index.js

format pagination

---

.storybook/config.js
.storybook/themeDecorator.js
package-lock.json
package.json
src/App.js
src/lib/nodes/RejectButton/index.jsx
src/lib/nodes/RejectButton/style.js
src/lib/nodes/Select/index.jsx
src/lib/nodes/Select/style.js
src/lib/nodes/index.js
src/stories/index.js
src/theme/index.jsx

Reject icon

---

src/lib/RejectionNote/index.jsx
src/lib/nodes/RejectActions/index.jsx
src/lib/nodes/RejectActions/style.js
src/lib/nodes/RejectButton/index.jsx
src/lib/nodes/RejectButton/style.js
src/lib/nodes/RejectTooltip/index.jsx
src/lib/nodes/index.js
src/stories/index.js

Rejection action component

---

src/lib/DocumentList/index.jsx
src/lib/DocumentList/style.js
src/lib/HeaderCollapse/index.jsx
src/lib/HeaderCollapse/style.js
src/lib/RejectionNote/index.jsx
src/lib/RejectionNote/style.js
src/stories/index.js

documentList component

---

src/lib/Table/components/Tbody/index.jsx
src/lib/Table/components/Tbody/style.js
src/lib/Table/components/Thead/style.js
src/stories/index.js

fix color header

---

package.json
src/lib/DropZone/index.jsx
src/lib/DropZone/style.js
src/lib/FilePreview/index.jsx
src/lib/FilePreview/style.js
src/lib/UploadDocuments/index.jsx
src/lib/UploadDocuments/style.js
src/stories/index.js
yarn.lock

UploadDocuments component

---

src/lib/nodes/TextAreaInput/index.jsx
src/lib/nodes/TextAreaInput/style.js
src/lib/nodes/index.js
src/stories/index.js

TextArea input

---

src/lib/nodes/CurrencyInput/index.jsx
src/lib/nodes/TextAreaInput/index.jsx
src/lib/nodes/TextAreaInput/style.js
src/lib/nodes/index.js
src/stories/index.js

Currency input

---

package.json
src/lib/DropZone/index.jsx
src/lib/FileFinder/index.jsx
src/lib/FileFinder/style.js
src/lib/FileThumbnail/index.jsx
src/lib/FileThumbnail/style.js
src/stories/index.js
yarn.lock

File thumbnail

---

src/lib/FileFinder/index.jsx
src/lib/FileThumbnail/style.js
src/lib/UploadDocuments/index.jsx
src/lib/nodes/SearchBar/index.jsx
src/stories/index.js

Multiple file upload

---

src/lib/HeaderCard/index.jsx
src/lib/nodes/IDCardUpload/PreviewID/index.jsx
src/lib/nodes/IDCardUpload/PreviewID/style.js
src/lib/nodes/IDCardUpload/UploadID/index.jsx
src/lib/nodes/IDCardUpload/UploadID/style.js
src/lib/nodes/IDCardUpload/index.jsx
src/lib/nodes/IDCardUpload/style.js
src/lib/nodes/ImageActions/index.jsx
src/lib/nodes/index.js
src/stories/index.js

Id card upload

---

src/lib/nodes/ListSignerRoles/SignerRolesStep/index.jsx
src/lib/nodes/ListSignerRoles/SignerRolesStep/style.js
src/lib/nodes/ListSignerRoles/data.json
src/lib/nodes/ListSignerRoles/index.jsx
src/lib/nodes/ListSignerRoles/style.js
src/lib/nodes/index.js
src/stories/index.js

Sidebar steps

---

dist/RejectionField/index.js
dist/nodes/RejectActions/index.js
src/lib/RejectionField/index.jsx
src/lib/nodes/RejectActions/index.jsx

Changes to hide the rejectAction components

---

src/lib/UploadDocuments/index.jsx

Permite cargar documentos o imagenes desde props

---

dist/nodes/RejectDocuments/index.js
dist/nodes/RejectDocuments/style.js
src/lib/nodes/RejectDocuments/index.jsx
src/lib/nodes/RejectDocuments/style.js
src/lib/nodes/index.js

Componente para rechazar documentos

---

dist/nodes/BaseNumberInput/index.js
dist/nodes/index.js
src/lib/nodes/BaseNumberInput/index.jsx
src/lib/nodes/index.js
src/stories/index.js

Add numberInput

---

dist/nodes/InputTable/index.js
dist/nodes/TextAreaInput/index.js
src/lib/nodes/InputTable/index.jsx
src/lib/nodes/TextAreaInput/index.jsx

Componente TextAreaInput no borraba el valor y ademas agregue el label del InputTable al momento de guardar.

TexAreaInput refrescar valor y InputTable enviar label al momento del handleChange

---

dist/InputStrings.js
dist/nodes/BaseNumberInput/index.js
dist/nodes/BaseTextInput/index.js
dist/nodes/InputTable/index.js
dist/nodes/TextAreaInput/index.js
src/lib/InputStrings.js
src/lib/nodes/BaseNumberInput/index.jsx
src/lib/nodes/BaseTextInput/index.jsx
src/lib/nodes/InputTable/index.jsx
src/lib/nodes/TextAreaInput/index.jsx

Muestro el nombre del campo cuando el campo se dejo vacio y es requerido

---

dist/RejectionField/index.js
dist/RejectionField/style.js
src/lib/RejectionField/index.jsx
src/lib/RejectionField/style.js
src/stories/index.js

Nueva funcionalidad para el componente RejectionField

---

dist/RejectionField/index.js
dist/RejectionNote/index.js
dist/RejectionNote/style.js
dist/nodes/RejectActions/index.js
dist/nodes/RejectButton/index.js
dist/nodes/RejectButton/style.js
dist/nodes/RejectDocuments/index.js
src/lib/RejectionField/index.jsx
src/lib/RejectionNote/index.jsx
src/lib/RejectionNote/style.js
src/lib/nodes/RejectActions/index.jsx
src/lib/nodes/RejectButton/index.jsx
src/lib/nodes/RejectButton/style.js
src/lib/nodes/RejectDocuments/index.jsx
src/stories/index.js

Agregar cambios de estilo cuando se muestra el icono de la nota de rechazo.
Agregar el comportamiento de deshacer el rechazo (sin afectar el comportamiento anterior del componente).

Adding undo rejection

---

dist/RejectionField/index.js
src/lib/RejectionField/index.jsx

- Cerrar el icono de rechazo al deshacer el rechazo.

Fix undo rejection

---

dist/RejectionField/index.js
dist/nodes/RejectActions/index.js
src/lib/RejectionField/index.jsx
src/lib/nodes/RejectActions/index.jsx

- Arreglar problema del icono de rechazo no se oculta.

Fix hidden reject icon

---

dist/RejectionField/index.js
dist/RejectionNote/index.js
dist/nodes/BaseInput/index.js
dist/nodes/BaseInput/style.js
dist/nodes/InputWrapper/index.js
dist/nodes/RejectActions/index.js
dist/nodes/RejectDocuments/index.js
src/hooks/useClickOutside.js
src/lib/RejectionField/index.jsx
src/lib/RejectionNote/index.jsx
src/lib/nodes/BaseInput/index.jsx
src/lib/nodes/BaseInput/style.js
src/lib/nodes/InputWrapper/index.jsx
src/lib/nodes/RejectActions/index.jsx
src/lib/nodes/RejectDocuments/index.jsx
src/stories/index.js

- Cerrar la nota al hacer click fuera de ella.
- No editar los documentos ni los campos si solo esta en modo lectura.
- Actualizar el input si se deshace el rechazo (se quedaba en rojo).
- Cambiar la posición del botón de la nota.

General rejection components fixes

---

dist/RejectionField/index.js
src/lib/RejectionField/index.jsx

- Arreglar problema, no se guardan las razones de rechazo.

Fix unsave rejection data

---

dist/FilePreview/index.js
dist/UploadDocuments/index.js
dist/nodes/RejectDocuments/index.js
src/lib/FilePreview/index.jsx
src/lib/UploadDocuments/index.jsx
src/lib/nodes/RejectDocuments/index.jsx
src/stories/index.js

-Fix para cargar documents que aveces no se visualizan correctamente en chrome.

Fix FilePreview

---

dist/nodes/InputTable/index.js
src/lib/nodes/InputTable/index.jsx

Agregar la propiedad "label" a los objetos de salida para que se puedan colocar los valores correctamente en el pdf

Agregar el campo label

---

dist/nodes/DynamicFields/component/CustomField.js
dist/nodes/DynamicFields/component/GroupFields.js
dist/nodes/DynamicFields/index.js
dist/nodes/DynamicFields/style.js
src/lib/nodes/DynamicFields/component/CustomField.jsx
src/lib/nodes/DynamicFields/component/GroupFields.jsx
src/lib/nodes/DynamicFields/index.jsx
src/lib/nodes/DynamicFields/style.js
src/lib/nodes/index.js
src/stories/index.js

Componente para generar inputs por firmantes

---

src/lib/nodes/BaseClabeInput/index.jsx
src/lib/nodes/BaseDatePicker/index.jsx
src/lib/nodes/index.js
src/stories/index.js

Add BaseClabeInput, format DatePicker

---

dist/Autocomplete/index.js
dist/Autocomplete/style.js
package.json
src/lib/Autocomplete/index.jsx
src/lib/Autocomplete/style.js
src/stories/index.js

fix autocompleate for single array

---

dist/Autocomplete/index.js
dist/Autocomplete/style.js
dist/FilePreview/style.js
package.json
src/lib/Autocomplete/index.jsx
src/lib/Autocomplete/style.js
src/lib/FilePreview/style.js
src/stories/index.js

https://github.com/FintecimalGit/fintecimal-react-components/commit/a04d973e288356d993f2a138853ff7e8c34172be

Fix file preview

---

dist/FilePreview/index.js
dist/nodes/CardApp/index.js
src/lib/FilePreview/index.jsx
src/lib/nodes/CardApp/index.jsx

-Corregi imagenes estiradas en FilePreview
-Corregi los proptypes para que no marquen warnings

Fix imagenes estiradas en FilePreview

---

dist/nodes/RejectDocuments/index.js
src/lib/nodes/RejectDocuments/index.jsx

- Agregar `multiple` al componente `RejectDocuments`

Adding multiple prop

---

dist/nodes/Select/index.js
dist/nodes/Select/style.js
src/lib/nodes/Select/index.jsx
src/lib/nodes/Select/style.js

Agregar espacio entre el label de texto largo y el select.
Antes:
Después:

Adding space in long placeholder

---

dist/DatePicker/index.js
src/lib/DatePicker/index.jsx

- Agregar un botón para limpiar el input si tiene un valor.

Adding clear button DatePicker

---

dist/nodes/ListSignerRoles/SignerRolesStep/index.js
dist/nodes/ListSignerRoles/data.js
src/lib/nodes/ListSignerRoles/SignerRolesStep/index.jsx
src/lib/nodes/ListSignerRoles/data.js

- Agregar la opción de ocultar un step en la lista.

Adding hidden step

---

dist/nodes/ImageActions/style.js
src/lib/nodes/ImageActions/style.js
src/stories/index.js

Fix imagenes distorcionadas para el componente de INE
Fixes #125 
-Imagenes distorcionadas para las imagenes que se generan desde FIDA en la revision de firmas.
- Code
- Bug fix
-Imagenes antes
-Imagenes ahora

Fix imagenes distorcionadas para el componente de INE

---

src/ui/LoginUI.js

Agregar las etiquetas `Correo` y `Contraseña` en el componente de Login.
- Code
Iniciar sesión.
Antes:
Después:

Adding input labels

---

dist/LoginUI.js

Actualizar el archivo de dist del Login.
- Code
Iniciar sesión.

Update dist login file

---

src/lib/nodes/SpecialInput/style.js

align flag icon

---

dist/nodes/BaseTextInput/index.js
dist/nodes/InputWrapper/index.js
dist/nodes/Select/index.js
src/lib/nodes/BaseTextInput/index.jsx
src/lib/nodes/InputWrapper/index.jsx
src/lib/nodes/Select/index.jsx

Agregar valor por defecto en los componentes `Select`, `BaseTextInput` y `InputWrapper`.
- Code
Mandarle como prop la variable `defaultValue`.

Adding defaultValue

---

dist/nodes/SpecialInput/style.js
src/lib/nodes/SpecialInput/style.js

Fix phone input style

---

dist/nodes/InputWrapper/index.js
dist/nodes/Select/index.js
src/lib/nodes/InputWrapper/index.jsx
src/lib/nodes/Select/index.jsx

Agregar la función `handleChange` cuando el valor cambie por medio del defaultValue.
- Code
Agregar valores por default.

Adding handleChange

---

dist/DocumentList/style.js
dist/nodes/BaseDatePicker/index.js
src/lib/DocumentList/style.js
src/lib/nodes/BaseDatePicker/index.jsx

-Agregue la opción de limpiar una fecha.
-Corregí los estilos de los estatus para el componente DocumentList
- Code
-DocumentList
-BaseDatePicker

Fix DatePicker and DocumentList

---

dist/nodes/BaseInput/style.js
dist/nodes/InputWrapper/index.js
dist/nodes/Select/index.js
dist/nodes/Select/style.js
src/lib/nodes/BaseInput/style.js
src/lib/nodes/Select/style.js
yarn.lock

Error en los estilos en Safari
* BaseInput
* Select
* BaseInput
* Select
* BaseInput
* Select
* BaseInput
* Select
- Code
Manual

Fix heht input

---

dist/nodes/SearchBar/style.js
src/lib/nodes/SearchBar/style.js

Actualizar el tamaño del componente `SearchBar`.
- Code

Updating searchBar height

---

dist/api/google.js
dist/api/keys.js
dist/nodes/BaseAddressInput/index.js
dist/nodes/BaseAddressInput/style.js
dist/nodes/BaseFullAddressInput/index.js
dist/nodes/BaseFullAddressInput/style.js
dist/nodes/index.js
package.json
src/lib/api/google.js
src/lib/api/keys.js
src/lib/nodes/BaseAddressInput/index.jsx
src/lib/nodes/BaseAddressInput/style.js
src/lib/nodes/BaseFullAddressInput/index.jsx
src/lib/nodes/BaseFullAddressInput/style.js
src/lib/nodes/index.js
src/stories/index.js

Agregar dos campos de tipo Dirección.
- Code

Address Input

---

dist/nodes/BaseCURPInput/index.js
dist/nodes/index.js
src/lib/nodes/BaseCURPInput/index.jsx
src/lib/nodes/BaseRFCInput/index.jsx
src/lib/nodes/index.js
src/stories/index.js

Disabled property added in RFC and CURP components
-RFC
-CURP

Disabled property added in RFC and CURP components

---

package-lock.json
package.json

Retornar a la version de material ui 4.3.3
- Code

Update material ui version 4.3.3

---

dist/nodes/BaseClabeInput/index.js
dist/nodes/BaseInput/index.js
dist/nodes/BasePhoneInput/index.js
dist/nodes/InputWrapper/index.js
dist/nodes/SpecialInput/index.js
src/lib/nodes/BaseClabeInput/index.jsx
src/lib/nodes/BaseInput/index.jsx
src/lib/nodes/BasePhoneInput/index.jsx
src/lib/nodes/InputWrapper/index.jsx
src/lib/nodes/SpecialInput/index.jsx
src/stories/index.js

Agregar variable maxLength en los input de telefono y clabe.
- Code
- Outreach

Max length inputs

---

dist/InputStrings.js
dist/nodes/BaseDatePicker/index.js
dist/nodes/BaseDatePicker/style.js
dist/nodes/InputTable/index.js
dist/nodes/Select/index.js
src/lib/InputStrings.js
src/lib/nodes/BaseDatePicker/index.jsx
src/lib/nodes/BaseDatePicker/style.js
src/lib/nodes/InputTable/index.jsx
src/lib/nodes/Select/index.jsx
src/stories/index.js

-Agregue la propiedad de required a los componentes BaseDatePicker, InputTable y Lista para que cuando se haga el submit detecte si esta vacío o tiene errores y no deje avanzar en formularios.
- Code
-Fecha validación
-Input table mensaje de error

Added required property to BaseDatePicker, InputTable and Select componets

---

dist/nodes/BaseDatePicker/index.js
dist/nodes/BasePhoneInput/index.js
src/lib/nodes/BaseDatePicker/index.jsx
src/lib/nodes/BasePhoneInput/index.jsx

Cambie el input de telefono para que solo acepte numeros y el de date para que no muestre la X cuando no se tiene permiso de editar

Cambios en input de telefono y date

---

dist/DocumentList/index.js
dist/DocumentList/status.js
src/lib/DocumentList/index.jsx
src/lib/DocumentList/status.js
src/stories/index.js
src/theme/index.jsx

Show progress on Document status

Show progress on Document status

---

dist/nodes/RejectDocuments/index.js
src/lib/nodes/RejectDocuments/index.jsx

Arreglando multiples imagenes en la vista de verificacion en los campos de documentos para el INE.

Fix multiple images

---

src/lib/nodes/CurrencyInput/index.jsx

https://www.loom.com/share/00675add30ff481f80ced4cd3b5bf281

Se agrego validacion para que se ejecutara onClear al no haber numeros.

---

dist/nodes/CurrencyInput/index.js

Input currency, ya se habia subido el codigo, solo faltaba subir el dist

Subiendo dist del input currency.

---

dist/nodes/CurrencyInput/index.js
src/lib/nodes/CurrencyInput/index.jsx

https://www.loom.com/share/c4e3c6fe7d754b91b16c70e5993aded3

Se agrego propiedad disabled al input currency.

---

dist/nodes/BaseDatePicker/index.js
src/lib/nodes/BaseDatePicker/index.jsx

- Se modifico la funcion de moment a la version que funciona, se agrego format

Se arreglo el formato de la fecha.

---

dist/nodes/BaseDatePicker/index.js
src/lib/nodes/BaseDatePicker/index.jsx

https://www.loom.com/share/25bd00bbbdbf4ca38a05c4416c8ce97e

Format date fix

---

dist/nodes/PercentageInput/index.js
dist/nodes/index.js
src/lib/nodes/PercentageInput/index.jsx
src/lib/nodes/index.js
src/stories/index.js

https://www.loom.com/share/7df13063f6794fd792da59ee5312cfcf

Percentage input

---

dist/nodes/CardApp/index.js
dist/nodes/CardApp/style.js
src/lib/nodes/CardApp/index.jsx
src/lib/nodes/CardApp/style.js

adding image instead icon.
- Code
Local.

adding image instead icon

---

dist/nodes/ListSignerRoles/data.js
dist/nodes/ListSignerRoles/index.js
dist/nodes/ListSignerRoles/style.js
src/lib/nodes/ListSignerRoles/data.js
src/lib/nodes/ListSignerRoles/index.jsx
src/lib/nodes/ListSignerRoles/style.js

https://www.loom.com/share/7493c4a83d1e4568b0c3d0ea51576c2b

Se agrego validacion para no hacer accion en steps.

---

dist/nodes/ListSignerRoles/index.js
dist/nodes/ListSignerRoles/style.js
src/lib/nodes/ListSignerRoles/index.jsx
src/lib/nodes/ListSignerRoles/style.js

- Se agrego validación para mostrar steps sin función como deshabitados

Se agrego color disabled a steps sin funcion.

---

dist/FilePreview/index.js
src/lib/FilePreview/index.jsx

- Se uso función para poder manejar archivo en iframe sin romper el limite de string
https://www.loom.com/share/84276263b28f43d3901f9dfa22f8c591

FilePreview PDF fix.

---

dist/FilePreview/style.js
src/lib/FilePreview/style.js

- Se modifico el estilo del input para mejor estetica.
Antes.
Despues.

Se modifico el style de filePreview.

---

dist/nodes/BaseInput/index.js
dist/nodes/BaseInput/style.js
src/lib/nodes/BaseInput/index.jsx
src/lib/nodes/BaseInput/style.js

Status style in BaseInput was changed to look same as design.
- fontFamily changed to Open sans
- fontSize, lineHeight and weight changed.
Local.

Status styles changed

---

dist/UploadDocuments/DeleteDialog/index.js
dist/UploadDocuments/DeleteDialog/style.js
dist/UploadDocuments/index.js
src/lib/UploadDocuments/DeleteDialog/index.jsx
src/lib/UploadDocuments/DeleteDialog/style.js
src/lib/UploadDocuments/index.jsx
src/stories/index.js

When user wanna delete the document a dialog will appear to ask if the user wanna delete the document.
- there is 2 ways to delete, one is delete only one page and the other ir delete all pages.
- Code
Local.
[Eliminado masivo y de pagina](https://www.loom.com/share/eca5f6c1160a4046a1cf1ca27473a52b)
[Estatus internos en componentes](https://www.loom.com/share/318134fc22d34880844c6bf9fbe2892e)

UploadDocuments with dialog to ask the user to delete the document

---

dist/FilePreview/index.js
dist/UploadDocuments/index.js
dist/nodes/PdfViewer/NavigationBar/index.js
dist/nodes/PdfViewer/NavigationBar/style.js
dist/nodes/PdfViewer/detectPdf.js
dist/nodes/PdfViewer/index.js
dist/nodes/PdfViewer/style.js
dist/nodes/index.js
package.json
src/lib/FilePreview/index.jsx
src/lib/UploadDocuments/index.jsx
src/lib/nodes/PdfViewer/NavigationBar/index.jsx
src/lib/nodes/PdfViewer/NavigationBar/style.js
src/lib/nodes/PdfViewer/detectPdf.js
src/lib/nodes/PdfViewer/index.jsx
src/lib/nodes/PdfViewer/style.js
src/lib/nodes/index.js
src/stories/index.js

PDF viewer created, this viewer only appear if the user does not have a pdf viewer in the browser.
- Code
Local.

PDF viewer created and added to UploadDocuments Component

---

dist/FilePreview/index.js
dist/nodes/PdfViewer/index.js
src/lib/FilePreview/index.jsx
src/lib/nodes/PdfViewer/index.jsx

…in each state changed
- Each page update load the pdf document again.
- no PDF documents fall down to pdf viewer.
- Code
Local.
[loom](https://www.loom.com/share/32435402d2a64b67b58f97bd7a314bcd)

fixing bugs, PNGs fall down to PdfViewer cases and pdf always update

---

dist/nodes/PdfViewer/NavigationBar/index.js
dist/nodes/PdfViewer/index.js
src/lib/nodes/PdfViewer/NavigationBar/index.jsx
src/lib/nodes/PdfViewer/index.jsx

- Fix: When user click enter to navigate to some page in pdf viewer, the save button is activated.
- Code
Local.

fix: Enter actual Page input  activate Guardar Button

---

dist/FileThumbnail/index.js
dist/nodes/RejectTooltip/index.js
src/lib/FileThumbnail/index.jsx
src/lib/nodes/RejectTooltip/index.jsx

- Pdf thumbnails are shown.
- click outside  rejected field  disable the reject button.
- Code
Local

Pdf thumbnails

---

dist/UploadDocuments/index.js
dist/nodes/RejectDocuments/index.js
dist/nodes/SearchBar/index.js
dist/nodes/SearchBar/style.js
src/lib/UploadDocuments/index.jsx
src/lib/nodes/RejectDocuments/index.jsx
src/lib/nodes/SearchBar/index.jsx
src/lib/nodes/SearchBar/style.js

- move to the file title when user click the file thumbnail.
- Enable click in searchIcon.
- Code
Local.
[The problem](https://www.loom.com/share/e0a9d8baea23420d81773b763e245b95)
[Solution](https://www.loom.com/share/210a6f030df843118c2f42f1ce41a279)
[The Problem](https://www.loom.com/share/589cf2628d68449cabe8a76efad0edc3)

Move to the file title when user click file thumbnail

---

dist/nodes/BaseCURPInput/index.js
dist/nodes/BaseClabeInput/index.js
dist/nodes/BaseEmailInput/index.js
dist/nodes/BaseInput/index.js
dist/nodes/BaseNumberInput/index.js
dist/nodes/BaseRFCInput/index.js
dist/nodes/BaseTextInput/index.js
dist/nodes/CurrencyInput/index.js
dist/nodes/InputWrapper/index.js
dist/nodes/PercentageInput/index.js
src/lib/nodes/BaseCURPInput/index.jsx
src/lib/nodes/BaseClabeInput/index.jsx
src/lib/nodes/BaseEmailInput/index.jsx
src/lib/nodes/BaseInput/index.jsx
src/lib/nodes/BaseNumberInput/index.jsx
src/lib/nodes/BaseRFCInput/index.jsx
src/lib/nodes/BaseTextInput/index.jsx
src/lib/nodes/CurrencyInput/index.jsx
src/lib/nodes/InputWrapper/index.jsx
src/lib/nodes/PercentageInput/index.jsx

- auto complete prop added to inputs. 
- By default this props is off due some errors caused by this prop on.
- Code
Local.

auto complete prop added to inputs

---

dist/nodes/SearchBar/index.js
src/lib/nodes/SearchBar/index.jsx

- Se agrego id para poder referenciarlo en currentTarget en el portal.
- Code
local.

Se agrego id a searchBar.

---

dist/nodes/BasePhoneInput/index.js
dist/nodes/InputWrapper/index.js
src/lib/nodes/BasePhoneInput/index.jsx
src/lib/nodes/InputWrapper/index.jsx

https://www.loom.com/share/9089040ce1894113a0b3e26575415c51
- Code
local

Se cambio el la funcion onchande a onblur.

---

dist/nodes/InputWrapper/index.js
src/lib/nodes/InputWrapper/index.jsx

Fix Error al guardar el value en el onBlur
- Code
local.

Fix con guardado de value en onBlur.

---

dist/FileFinder/index.js
dist/UploadDocuments/index.js
dist/nodes/BasePhoneInput/index.js
dist/nodes/SpecialInput/index.js
src/lib/FileFinder/index.jsx
src/lib/UploadDocuments/index.jsx
src/lib/nodes/BasePhoneInput/index.jsx
src/lib/nodes/SpecialInput/index.jsx

- comment the search bar in documents
- Convert url string to array to avoid errors when user delete the document.
- Code
Local..
[Loom](https://www.loom.com/share/5b8de6350ff74105933d673ef6232c21)

comment search bar and convert url string to array

---

dist/FileFinder/Drag/index.js
dist/FileThumbnail/index.js
dist/UploadDocuments/index.js
src/lib/FileFinder/Drag/index.jsx
src/lib/FileThumbnail/index.jsx
src/lib/FileThumbnail/style.js
src/lib/UploadDocuments/index.jsx

- Add border color when document is hover the drop.
- Handle Errors added when set the files.
- Code
Local.

add border color in drop

---

dist/IneEditor/index.js
dist/UploadDocuments/index.js
dist/nodes/RejectDocuments/index.js
src/lib/IneEditor/index.jsx
src/lib/UploadDocuments/index.jsx
src/lib/nodes/RejectDocuments/index.jsx

An image editor that only appear for ine types.
the editor contains the following:
- Crop
- Rotate
[Ine editor](https://www.loom.com/share/67d69b091968458e88de346a48d2761e)
- Code
Local.

Editor ine

---

dist/IneEditor/index.js
src/lib/IneEditor/index.jsx

Get the first page of an array.
If the client upload an pdf with multiple pages, the result will be an array not a string.
- Code
Local.

fix arrays in crop

---

dist/nodes/RejectDocuments/index.js
src/lib/nodes/RejectDocuments/index.jsx

Fix the prefix in reject document names.
- Code
Local.

fix the prefix name in rejectDocuments

---

dist/nodes/InputTable/components/CustomField.js
src/lib/nodes/InputTable/components/CustomField.jsx

https://www.loom.com/share/3c51f71184ab4831a3bf5d83afa36e86
- Code
local.

Se agrego el input de currency al inputTable.

---

dist/nodes/SearchBar/index.js
src/lib/nodes/SearchBar/index.jsx

https://www.loom.com/share/3b217328bc044abfa04d07e99811d19e
- Code
local.

Se agrego el id al icono de busqueda.

---

dist/nodes/CardApp/index.js
dist/nodes/CardApp/style.js
src/lib/nodes/CardApp/index.jsx
src/lib/nodes/CardApp/style.js
src/stories/index.js

Improve card app component to support notifications.
- Code
- Outreach
Storybook ;)

Card app notification

---

dist/nodes/CardApp/index.js
dist/nodes/CardApp/style.js
src/lib/nodes/CardApp/index.jsx
src/lib/nodes/CardApp/style.js

Fix visual button.
- Code
- Outreach
storybook

fix(card app notification): Visual button fixed

---

dist/DocumentCrop/ImageEditor/index.js
dist/DocumentCrop/style.js
src/lib/DocumentCrop/ImageEditor/index.jsx
src/lib/DocumentCrop/style.js

Add new buttons to ine editor:
- move image
- draw crop canvas
- Zoom out
- Zoom in
Increase the ine editor height 
[New Ine editor buttons](https://www.loom.com/share/f4330779797343f18bf1ae19774ec799)
- Code
Local.

add move, crop and Zoom out and in buttons

---

dist/nodes/RejectActions/index.js
dist/nodes/RejectTooltip/index.js
src/lib/nodes/RejectActions/index.jsx
src/lib/nodes/RejectTooltip/index.jsx

Add defaultNotes to rejections
[defaultNotes in rejections](https://www.loom.com/share/4b1ca6f332e5439da731b3ab7285e94a)
- Code
Local.

add defaultNotes to rejections

---

dist/DocumentCrop/Header/index.js
dist/DocumentCrop/ImageEditor/index.js
dist/DocumentCrop/ImageEditor/style.js
dist/DocumentCrop/Text/index.js
dist/DocumentCrop/style.js
src/lib/DocumentCrop/Header/index.jsx
src/lib/DocumentCrop/ImageEditor/index.jsx
src/lib/DocumentCrop/ImageEditor/style.js
src/lib/DocumentCrop/Text/index.jsx
src/lib/DocumentCrop/style.js

- Adjust the position of tools in Ine editor.
- Separate move and crop buttons
- Add new rotation left button.
[Adjust ine editor tools](https://www.loom.com/share/bf7d8147d2f44fd5870316750ae5a8a3)
Storybook.

adjust the position of tools

---

dist/DocumentCrop/ImageEditor/index.js
src/lib/DocumentCrop/ImageEditor/index.jsx

- Change Ine editor button colors
- Code
Storrybook

Change ine editor button colors

---

src/lib/DocumentCrop/ImageEditor/style.js

- Fix the height in Ine editor tools
- Code
Storybook

Fix the height in Ine editor tools

---

dist/DocumentCrop/ImageEditor/style.js

Fix the height in Ine Editorr

---

dist/DocumentCrop/ImageEditor/index.js
dist/DocumentCrop/ImageEditor/style.js
dist/DocumentCrop/style.js
src/lib/DocumentCrop/ImageEditor/index.jsx
src/lib/DocumentCrop/ImageEditor/style.js
src/lib/DocumentCrop/style.js

- Change Ine Editor Style.
- Crop button was removed.
- Cancelar and Listo was changed to CloseIcon and CheckIcon
- Cancelar was separated from main grid to be floated to left top corner.
Storybook.

change ine editor tools style

---

dist/DocumentCrop/ImageEditor/index.js
src/lib/DocumentCrop/ImageEditor/index.jsx

- Replace CheckIcon for OK word in Ine editor
Storybook.

Replace checkIcon for OK word in Ine editor

---

dist/DocumentCrop/ImageEditor/index.js
dist/nodes/RejectDocuments/index.js
dist/nodes/RejectTooltip/index.js
src/lib/DocumentCrop/ImageEditor/index.jsx
src/lib/nodes/RejectDocuments/index.jsx
src/lib/nodes/RejectTooltip/index.jsx

- set reject default notes in RejectDocuments.
- In onChangeReason change the value with name to evaluate.
[Set rejectDefaultNotes](https://www.loom.com/share/c0ac4ff8b62a4ee8a67b9d2a16014971)
- Code
Local.

set rejectDefaultNotes in RejectDocuments

---

dist/RejectionField/index.js
dist/nodes/RejectDocuments/index.js
src/lib/RejectionField/index.jsx
src/lib/nodes/RejectDocuments/index.jsx

https://www.loom.com/share/dde9bd1db5294f7ebc1c30cb60272635
- Code
local

Se esconden botones de rechazo dependiendo de prop

---

dist/nodes/RejectTooltip/index.js
src/lib/nodes/RejectTooltip/index.jsx

- Add label title to rejcts reasons tootltip.
- Code
Local.

add label prop in reject tooltip

---

dist/FilePreview/index.js
dist/nodes/DocumentEditor/index.js
dist/nodes/DocumentEditor/style.js
dist/nodes/RejectDocuments/index.js
src/lib/FilePreview/index.jsx
src/lib/nodes/DocumentEditor/index.jsx
src/lib/nodes/DocumentEditor/style.js
src/lib/nodes/RejectDocuments/index.jsx
src/stories/index.js

- Create document editor to edit images.
- Code
Local.

create document editor

---

dist/nodes/BaseCURPInput/index.js
package-lock.json
package.json
src/lib/nodes/BaseCURPInput/index.jsx

Added CURP validation with this dependency:
https://github.com/manuelmhtr/validate-curp
- Code
- Outreach

added BaseCURP validation

---

dist/nodes/InputTableSigners/components/CsvReader.js
dist/nodes/InputTableSigners/components/CustomField.js
dist/nodes/InputTableSigners/components/Fields/index.js
dist/nodes/InputTableSigners/components/Fields/style.js
dist/nodes/InputTableSigners/defaults.js
dist/nodes/InputTableSigners/index.js
dist/nodes/InputTableSigners/style.js
dist/nodes/InputTableSigners/utils.js
dist/nodes/index.js
src/lib/nodes/InputTableSigners/components/CsvReader.jsx
src/lib/nodes/InputTableSigners/components/CustomField.jsx
src/lib/nodes/InputTableSigners/components/Fields/index.jsx
src/lib/nodes/InputTableSigners/components/Fields/style.js
src/lib/nodes/InputTableSigners/defaults.js
src/lib/nodes/InputTableSigners/index.jsx
src/lib/nodes/InputTableSigners/style.js
src/lib/nodes/InputTableSigners/utils.js
src/lib/nodes/index.js
src/stories/index.js

- Se agrego un nuevo campo de tipo tabla donde la tabla se muestra arriba y los campos se piden abajo y no se necesita de momento leer ningun csv
- Code
Local - Storybook

Se creo tabla para guardar firmantes.

---

dist/nodes/InputTableSigners/components/CustomField.js
dist/nodes/InputTableSigners/components/Fields/BaseDatePicker/index.js
dist/nodes/InputTableSigners/components/Fields/BaseDatePicker/style.js
dist/nodes/InputTableSigners/components/Fields/index.js
dist/nodes/InputTableSigners/defaults.js
dist/nodes/InputTableSigners/index.js
dist/nodes/InputTableSigners/utils.js
dist/nodes/InputWrapper/index.js
src/lib/nodes/InputTableSigners/components/CustomField.jsx
src/lib/nodes/InputTableSigners/components/Fields/BaseDatePicker/index.jsx
src/lib/nodes/InputTableSigners/components/Fields/BaseDatePicker/style.js
src/lib/nodes/InputTableSigners/components/Fields/index.jsx
src/lib/nodes/InputTableSigners/defaults.js
src/lib/nodes/InputTableSigners/index.jsx
src/lib/nodes/InputTableSigners/utils.js
src/lib/nodes/InputWrapper/index.jsx

- Se arreglo bug en campos de tipo fecha en tabla de firmantes
- Code
storybook

Table signers date

---

dist/Table/components/Tbody/index.js
dist/Table/components/Tbody/style.js
dist/Table/components/Thead/index.js
dist/Table/components/Thead/style.js
dist/nodes/InputTableSigners/style.js
src/lib/Table/components/Tbody/index.jsx
src/lib/Table/components/Tbody/style.js
src/lib/Table/components/Thead/index.jsx
src/lib/Table/components/Thead/style.js
src/lib/nodes/InputTableSigners/style.js

- Responsive table signers
- overFlowX added
- Fontsize changed when screen is smaller.
- Code
Storybook.

Responsive table signers

---

dist/FilePreview/HiddenDocument/index.js
dist/FilePreview/HiddenDocument/style.js
dist/FilePreview/index.js
dist/FilePreview/style.js
dist/SignersCarousel/index.js
dist/SignersCarousel/style.js
src/lib/FilePreview/HiddenDocument/index.jsx
src/lib/FilePreview/HiddenDocument/style.js
src/lib/FilePreview/index.jsx
src/lib/FilePreview/style.js
src/lib/SignersCarousel/index.jsx
src/lib/SignersCarousel/style.js
src/stories/index.js

[Loom](https://www.loom.com/share/70657e86c4124b00b917287e63c828c6)

signerscarousel added to filePreview

---

dist/FilePreview/index.js
dist/SignersCarousel/index.js
dist/SignersCarousel/style.js
src/stories/index.js

fix signersCarousel

---

dist/nodes/BasePhoneInput/index.js
src/lib/nodes/BasePhoneInput/index.jsx

- Fix phone input
- Code
Local.

fix phone input

---

src/lib/nodes/BaseRFCFisicoInput/index.jsx
src/lib/nodes/BaseRFCMoralInput/index.jsx
src/lib/nodes/index.js
src/stories/index.js

https://www.loom.com/share/58c1211cbd8342568c8e5a7592ff513f
- Code
local

Se crearon campos para rfc moral y fisico separados.

---

dist/nodes/BaseRFCFisicoInput/index.js
dist/nodes/BaseRFCMoralInput/index.js
dist/nodes/InputTableSigners/components/Fields/index.js
dist/nodes/InputTableSigners/defaults.js
dist/nodes/InputTableSigners/utils.js
dist/nodes/index.js
src/lib/nodes/InputTableSigners/components/Fields/index.jsx
src/lib/nodes/InputTableSigners/defaults.js
src/lib/nodes/InputTableSigners/utils.js

- Se agrego dist con el cambio del RFC para morales y fisicas.
- La tabla de firmantes no acepta campos de tipo lista, se agrego esa funcionalidad
- Code
local

Se agrego dist del RFC para moral y fisico y Fix de lista en tabla.

---

dist/FilePreview/index.js
dist/FilePreview/style.js
dist/nodes/RejectDocuments/index.js
src/lib/FilePreview/index.jsx
src/lib/FilePreview/style.js
src/lib/nodes/RejectDocuments/index.jsx
src/stories/index.js

- Validation seal added
- Code
Local.

valid docuument certificaction

---

dist/FileThumbnail/index.js
dist/nodes/Maps/conf.js
dist/nodes/Maps/index.js
dist/nodes/SignatureMap/geoCoding.js
src/lib/FileThumbnail/index.jsx
src/lib/nodes/Maps/conf.js
src/lib/nodes/Maps/index.jsx
src/lib/nodes/SignatureMap/geoCoding.js

- Fix values to use in validation document.
- Code
Local.

Fix errors to use in validDocuments

---

dist/nodes/BaseDatePicker/index.js
src/lib/nodes/BaseDatePicker/index.jsx

Agregado fix en basedatepicker con bug que no asisgnaba una fecha vacia
- Code
local

Fixed value to null

---

dist/DocumentCrop/ImageEditor/index.js
src/lib/DocumentCrop/ImageEditor/index.jsx

- When image is cropped the respective mime is added
- Code
Local.

change file type when image is cropped

---

dist/InputStrings.js
dist/commons/exampleList.js
dist/nodes/Radio/index.js
dist/nodes/Radio/style.js
dist/nodes/index.js
src/lib/InputStrings.js
src/lib/commons/exampleList.js
src/lib/nodes/Radio/index.jsx
src/lib/nodes/Radio/style.js
src/lib/nodes/index.js
src/stories/index.js

Se agregó un nuevo campo de tipo radiogroup para visualizar campos con mas de una opcion, las cuales pueden llegar a ser extensas.
- Code
Local
Test

Nuevo campo de tipo radiogroup

---

dist/nodes/InputTableSigners/components/Fields/index.js
dist/nodes/InputTableSigners/defaults.js
dist/nodes/InputTableSigners/index.js
dist/nodes/InputTableSigners/utils.js
src/lib/nodes/InputTableSigners/components/Fields/index.jsx
src/lib/nodes/InputTableSigners/defaults.js
src/lib/nodes/InputTableSigners/index.jsx
src/lib/nodes/InputTableSigners/utils.js
src/stories/index.js

https://www.loom.com/share/34abf7761d8b436db3665de0d6336ccb
- Code
local

Se agrego condicionales a la tabla de firmantes.

---

src/lib/RejectionField/component/CustomField.jsx
src/lib/nodes/Radio/index.jsx

Agegado tipo radiogroup a los rejectfields
- Code
local

Fix para agregar el field de tipo radiogroup a los rejectedFields

---

dist/RejectionField/component/CustomField.js
dist/nodes/Radio/index.js

Fix dist radiogroup field to rejectFields
- Code

Fix dist radiogroup

---

dist/Liveness/LivenessCarousel/index.js
dist/Liveness/LivenessCarousel/style.js
dist/Liveness/LivenessVideo/index.js
dist/Liveness/LivenessVideo/style.js
dist/Liveness/index.js
dist/Liveness/style.js
src/lib/Liveness/LivenessCarousel/index.jsx
src/lib/Liveness/LivenessCarousel/style.js
src/lib/Liveness/LivenessVideo/index.jsx
src/lib/Liveness/LivenessVideo/style.js
src/lib/Liveness/index.jsx
src/lib/Liveness/style.js
src/stories/index.js

- New compnent to see liveness, video and ines
- Code
Local.

Liveness component created

---

dist/Liveness/LivenessCarousel/index.js
dist/Liveness/LivenessCarousel/style.js
dist/Liveness/index.js
src/lib/Liveness/LivenessCarousel/index.jsx
src/lib/Liveness/LivenessCarousel/style.js
src/lib/Liveness/index.jsx
src/stories/index.js

Improving liveness component
- Code

improving liveness component

---

dist/Liveness/LivenessCarousel/index.js
dist/Liveness/LivenessCarousel/style.js
dist/Liveness/LivenessVideo/style.js
dist/Liveness/index.js
dist/Liveness/style.js
src/lib/Liveness/LivenessCarousel/index.jsx
src/lib/Liveness/LivenessCarousel/style.js
src/lib/Liveness/LivenessVideo/style.js
src/lib/Liveness/index.jsx
src/lib/Liveness/style.js
src/stories/index.js

- Border in video component
- guide in liveness carousel
- center ines to video
- Code
- Outreach

improving liveness style

---

dist/ShortTable/components/Tbody/index.js
dist/ShortTable/components/Tbody/style.js
dist/ShortTable/components/Thead/index.js
dist/ShortTable/components/Thead/style.js
dist/ShortTable/index.js
dist/ShortTable/style.js
dist/nodes/InputTableSigners/defaults.js
dist/nodes/InputTableSigners/index.js
src/lib/ShortTable/components/Tbody/index.jsx
src/lib/ShortTable/components/Tbody/style.js
src/lib/ShortTable/components/Thead/index.jsx
src/lib/ShortTable/components/Thead/style.js
src/lib/ShortTable/index.jsx
src/lib/ShortTable/style.js
src/lib/nodes/InputTableSigners/defaults.js
src/lib/nodes/InputTableSigners/index.jsx

https://www.loom.com/share/54da2848a8fb4a0dbc1d1a9c93934753
- Code
local

Se acortan los headers para que la tabla no se salga del margen.

---

dist/ShortTable/components/Tbody/index.js
dist/ShortTable/components/Thead/index.js
dist/ShortTable/index.js
dist/nodes/InputTableSigners/index.js
src/lib/ShortTable/components/Tbody/index.jsx
src/lib/ShortTable/components/Thead/index.jsx
src/lib/ShortTable/index.jsx
src/lib/nodes/InputTableSigners/index.jsx
src/stories/index.js

https://www.loom.com/share/8e7a8f467a2a4d5ea37adbd65e0d27e3
- Code
Storybook

Se agrego prop a shortTable para hacer configurable los Headers.

---

src/lib/Liveness/index.jsx
src/lib/Liveness/style.js

Error fix Liveness

---

dist/UploadInvoices/DeleteDialog/index.js
dist/UploadInvoices/DeleteDialog/style.js
dist/UploadInvoices/index.js
dist/UploadInvoices/style.js
src/lib/UploadInvoices/DeleteDialog/index.jsx
src/lib/UploadInvoices/DeleteDialog/style.js
src/lib/UploadInvoices/index.jsx
src/lib/UploadInvoices/style.js

invoice component

---

dist/UploadInvoices/index.js
src/lib/UploadInvoices/index.jsx

fix handleonDelete error in uploadInvocies
- Code
- Outreach

fix handleonDelete error in uploadInvocies

---

dist/UploadInvoices/index.js
src/lib/UploadInvoices/index.jsx

invoices uuid document

---

dist/ShortTable/components/Tbody/index.js
dist/ShortTable/components/Thead/index.js
dist/ShortTable/index.js
dist/nodes/InputTableSigners/components/Fields/index.js
dist/nodes/InputTableSigners/index.js
dist/nodes/RejectionInputTableSigners/component/CustomField.js
dist/nodes/RejectionInputTableSigners/index.js
dist/nodes/RejectionInputTableSigners/style.js
src/lib/ShortTable/components/Tbody/index.jsx
src/lib/ShortTable/components/Thead/index.jsx
src/lib/ShortTable/index.jsx
src/lib/nodes/InputTableSigners/components/Fields/index.jsx
src/lib/nodes/InputTableSigners/index.jsx
src/lib/nodes/RejectionInputTableSigners/component/CustomField.jsx
src/lib/nodes/RejectionInputTableSigners/index.jsx
src/lib/nodes/RejectionInputTableSigners/style.js

Create RejectionInputTableSigners
- Code
- Outreach

disable input table signers

---

dist/nodes/RejectionInputTableSigners/defaults.js
dist/nodes/RejectionInputTableSigners/index.js
src/lib/nodes/RejectionInputTableSigners/defaults.js
src/lib/nodes/RejectionInputTableSigners/index.jsx

fix Rejection input table signers
- Code
- Outreach

fix Rejection input table signers

---

dist/ShortTable/components/Tbody/index.js
dist/ShortTable/components/Thead/index.js
dist/ShortTable/index.js
dist/nodes/InputTableSigners/components/Fields/index.js
dist/nodes/InputTableSigners/index.js
dist/nodes/RejectionInputTableSigners/index.js
src/lib/ShortTable/components/Tbody/index.jsx
src/lib/ShortTable/components/Thead/index.jsx
src/lib/ShortTable/index.jsx
src/lib/nodes/InputTableSigners/components/Fields/index.jsx
src/lib/nodes/InputTableSigners/index.jsx
src/lib/nodes/RejectionInputTableSigners/index.jsx

fix disabled name
- Code
- Outreach

inputTableSigners fix disabled name

---

dist/nodes/SearchBar/index.js
src/lib/nodes/SearchBar/index.jsx

- Searchbar clear button
- Code
- Outreach

search bar button clear

---

dist/nodes/InputTableSelect/components/CustomField/index.js
dist/nodes/InputTableSelect/components/Fields/index.js
dist/nodes/InputTableSelect/components/Fields/useStyles.js
dist/nodes/InputTableSelect/components/Table/components/Tbody/index.js
dist/nodes/InputTableSelect/components/Table/components/Tbody/useStyles.js
dist/nodes/InputTableSelect/components/Table/components/Thead/index.js
dist/nodes/InputTableSelect/components/Table/components/Thead/useStyles.js
dist/nodes/InputTableSelect/components/Table/index.js
dist/nodes/InputTableSelect/components/Table/useStyles.js
dist/nodes/InputTableSelect/defaults.js
dist/nodes/InputTableSelect/index.js
dist/nodes/InputTableSelect/useStyles.js
dist/nodes/InputTableSelect/utils.js
dist/nodes/index.js
src/lib/nodes/InputTableSelect/components/CustomField/index.jsx
src/lib/nodes/InputTableSelect/components/Fields/index.jsx
src/lib/nodes/InputTableSelect/components/Fields/useStyles.js
src/lib/nodes/InputTableSelect/components/Table/components/Tbody/index.jsx
src/lib/nodes/InputTableSelect/components/Table/components/Tbody/useStyles.js
src/lib/nodes/InputTableSelect/components/Table/components/Thead/index.jsx
src/lib/nodes/InputTableSelect/components/Table/components/Thead/useStyles.js
src/lib/nodes/InputTableSelect/components/Table/index.jsx
src/lib/nodes/InputTableSelect/components/Table/useStyles.js
src/lib/nodes/InputTableSelect/defaults.js
src/lib/nodes/InputTableSelect/index.jsx
src/lib/nodes/InputTableSelect/useStyles.js
src/lib/nodes/InputTableSelect/utils.js
src/lib/nodes/index.js
src/stories/index.js

Nuevo campo de tipo Input table select
- Code
loca-test

Agregado campo de tipo Input table select

---

dist/ShortTable/components/Tbody/index.js
dist/ShortTable/components/Thead/index.js
dist/ShortTable/index.js
dist/nodes/RejectInputTableSigners/components/CsvReader.js
dist/nodes/RejectInputTableSigners/components/CustomField.js
dist/nodes/RejectInputTableSigners/components/Fields/BaseDatePicker/index.js
dist/nodes/RejectInputTableSigners/components/Fields/BaseDatePicker/style.js
dist/nodes/RejectInputTableSigners/components/Fields/index.js
dist/nodes/RejectInputTableSigners/components/Fields/style.js
dist/nodes/RejectInputTableSigners/defaults.js
dist/nodes/RejectInputTableSigners/index.js
dist/nodes/RejectInputTableSigners/style.js
dist/nodes/RejectInputTableSigners/utils.js
dist/nodes/RejectionInputTableSigners/index.js
src/lib/ShortTable/components/Tbody/index.jsx
src/lib/ShortTable/components/Thead/index.jsx
src/lib/ShortTable/index.jsx
src/lib/nodes/RejectInputTableSigners/components/CsvReader.jsx
src/lib/nodes/RejectInputTableSigners/components/CustomField.jsx
src/lib/nodes/RejectInputTableSigners/components/Fields/BaseDatePicker/index.jsx
src/lib/nodes/RejectInputTableSigners/components/Fields/BaseDatePicker/style.js
src/lib/nodes/RejectInputTableSigners/components/Fields/index.jsx
src/lib/nodes/RejectInputTableSigners/components/Fields/style.js
src/lib/nodes/RejectInputTableSigners/defaults.js
src/lib/nodes/RejectInputTableSigners/index.jsx
src/lib/nodes/RejectInputTableSigners/style.js
src/lib/nodes/RejectInputTableSigners/utils.js
src/lib/nodes/RejectionInputTableSigners/index.jsx
src/stories/index.js

Feauture: InputTableSigners no editable en validacion/verificacion
- Code
local
test

Feauture: Table signers no editable en validacion/verificacion

---

dist/nodes/InputResponseChatgpt/index.js
dist/nodes/InputResponseChatgpt/style.js

Agregado dist de PR anterior (formato en value de chatgpt)
- Code
- Outreach

Agregado dist de formatted chatgpt value

---

dist/UploadDocuments/index.js
src/lib/UploadDocuments/index.jsx

Add verify again
- Code
- Outreach

add verify again

---

src/lib/nodes/InputTableSelect/components/CustomField/index.jsx
src/lib/nodes/InputTableSigners/components/CustomField.jsx
src/lib/nodes/RejectInputTableSigners/components/CustomField.jsx

Added radiogroup input to inputTableSigners type. 
- Code
local

Added radiogroup to inputTableSigners type

---

dist/nodes/InputTableSelect/components/CustomField/index.js
dist/nodes/InputTableSigners/components/CustomField.js
dist/nodes/RejectInputTableSigners/components/CustomField.js
src/lib/nodes/InputTableSelect/components/CustomField/index.jsx

Added radiogroup imp
- Code
- Outreach

Added inpu rado to td

---

dist/nodes/InputTableSigners/components/CustomField.js
dist/nodes/RejectInputTableSigners/components/CustomField.js
src/lib/nodes/InputTableSigners/components/CustomField.jsx
src/lib/nodes/RejectInputTableSigners/components/CustomField.jsx

Fix: Solucionado error de campo de tipo curp no requred dentro de las campos de tipo InputTableSigners
- Code
loca-prod.

Fix Curp field required en tablas

---

dist/nodes/RejectTooltip/index.js
src/lib/nodes/RejectTooltip/index.jsx

reject tooltips

---

package-lock.json
package.json
yarn.lock

update material ui packages
- Code
- Outreach

update matterial ui

---

dist/RejectionField/component/CustomField.js
dist/nodes/CurrencyInput/index.js
dist/nodes/InputCheckbox/index.js
dist/nodes/InputCheckbox/style.js
dist/nodes/InputCheckbox/useStyles.js
dist/nodes/index.js
src/lib/RejectionField/component/CustomField.jsx
src/lib/commons/exampleList.js
src/lib/nodes/CurrencyInput/index.jsx
src/lib/nodes/InputCheckbox/index.jsx
src/lib/nodes/InputCheckbox/style.js
src/lib/nodes/index.js
src/stories/index.js

https://www.loom.com/share/9e2f5da2c7c644a594b8ff87860d4759
- Code
local

Se agrego nuevo campo inputCheckbox.

---

package.json

Se regreso a la version anterior del material ui.

---

dist/nodes/CardApp/style.js
src/lib/nodes/CardApp/style.js

palette.tertiary.main eliminado

---

src/theme/index.jsx

fix material ui

---

package.json
src/theme/index.jsx

Se regreso la version de material ui

---

package-lock.json

Fix Versiones.

---

dist/nodes/InputMatriz/components/CsvReader.js
dist/nodes/InputMatriz/components/CustomField.js
dist/nodes/InputMatriz/components/Fields/BaseDatePicker/index.js
dist/nodes/InputMatriz/components/Fields/BaseDatePicker/style.js
dist/nodes/InputMatriz/components/Fields/index.js
dist/nodes/InputMatriz/components/Fields/style.js
dist/nodes/InputMatriz/defaults.js
dist/nodes/InputMatriz/index.js
dist/nodes/InputMatriz/style.js
dist/nodes/InputMatriz/utils.js
dist/nodes/index.js
src/lib/nodes/InputMatriz/components/CsvReader.jsx
src/lib/nodes/InputMatriz/components/CustomField.jsx
src/lib/nodes/InputMatriz/components/Fields/BaseDatePicker/index.jsx
src/lib/nodes/InputMatriz/components/Fields/BaseDatePicker/style.js
src/lib/nodes/InputMatriz/components/Fields/index.jsx
src/lib/nodes/InputMatriz/components/Fields/style.js
src/lib/nodes/InputMatriz/defaults.js
src/lib/nodes/InputMatriz/index.jsx
src/lib/nodes/InputMatriz/style.js
src/lib/nodes/InputMatriz/utils.js
src/lib/nodes/index.js
src/stories/index.js

https://www.loom.com/share/d21a889b50dc48b389e8b529bbef8820
- Code
local

Se agrego input para matriz de perfilamiento.

---

dist/nodes/InputMatriz/defaults.js
dist/nodes/InputMatriz/index.js
src/lib/nodes/InputMatriz/defaults.js
src/lib/nodes/InputMatriz/index.jsx

Se arreglo los headers maximos en InputMatriz y se agrego default data cuando no hay bancos aceptados
- Code
local

Se arreglo los headers maximos en InputMatriz

---

dist/nodes/InputMatriz/defaults.js
dist/nodes/InputMatriz/index.js
src/lib/nodes/InputMatriz/defaults.js
src/lib/nodes/InputMatriz/index.jsx

Fix new format matriz

---

dist/nodes/TextAreaInput/index.js
src/lib/nodes/TextAreaInput/index.jsx

fix: Se ejecuta el hanldeChange en el onBlur.

---

src/lib/nodes/SearchInput/index.jsx
src/lib/nodes/SearchInput/style.js
src/lib/nodes/index.js
src/stories/index.js

https://github.com/user-attachments/assets/172a3c19-08e1-4044-abe9-685d44043a24
- Code
storybook

feat: Se creo nuevo componente para buscar en usuarios en campo

---

dist/nodes/SearchInput/index.js
dist/nodes/SearchInput/style.js
dist/nodes/index.js

feat: Se agregan los js del dist para el campo de searchInput
- Code
local

feat: Se agregan los js del dist para el campo de searchInput

---

dist/nodes/SearchInput/style.js
src/lib/nodes/SearchInput/style.js

fix: Se arreglaron estilos de SearchInput para que no luzca transparente
- Code
storybook

fix: Se arreglaron estilos de SearchInput para que no luzca transparente

---

dist/nodes/SearchInput/index.js
src/lib/nodes/SearchInput/index.jsx

fix: Agregando id al value de la busqueda

---

dist/nodes/CurrencyInput/index.js
src/lib/nodes/CurrencyInput/index.jsx

fix: Se guarda la currency en el onblur
- Code
local

fix: Se guarda la currency en el onblur

---

dist/InputStrings.js
dist/nodes/InputNSS/index.js
dist/nodes/InputNSS/validator.js
src/lib/InputStrings.js
src/lib/nodes/InputNSS/index.jsx
src/lib/nodes/InputNSS/validator.js
src/stories/index.js

New input nss

---

dist/nodes/InputNSS/index.js
src/lib/nodes/InputNSS/index.jsx

fixed default export

---

dist/nodes/InputNSS/index.js
src/lib/nodes/InputNSS/index.jsx

Fix nss isValid

---

dist/UploadDocuments/index.js
src/lib/UploadDocuments/index.jsx

++ FIxed order when a document is drop, so its queed
- Code
- Outreach

[FIX] Keep ordered doccuments on drop
